<?php

/**
 * implements hook_mail_alter()
 *
 * @param $message
 */
function halle96_mail_settings_mail_alter(&$message) {
  // Revert Drupal's overriding of the "from" address so e.g.
  // Webform or rules can define a custom sender address
  // https://www.drupal.org/project/webform/issues/461324#comment-11569033
  if (isset($message['headers']['Reply-To'])) {
    $message['headers']['From'] = $message['headers']['Reply-To'];
    $message['headers']['Sender'] = $message['headers']['Reply-To'];
    $message['headers']['Errors-To'] = $message['headers']['Reply-To'];
    $message['headers']['Return-Path'] = $message['headers']['Reply-To'];
  }
}
