<?php


/**
 * Implements hook_libraries_info().
 */
function hannoverimpuls_dropdown_libraries_info() {

  $libraries['smartmenus'] = [
    'name' => 'Smartmenus',
    'vendor url' => 'https://github.com/vadikom/smartmenus/releases',
    'download url' => 'https://github.com/vadikom/smartmenus/archive/refs/tags/1.0.1.zip',
    'version callback' => 'simple_version_callback',
    'files' => [
      'js' => ['jquery.smartmenus.min.js'],
      'css' => ['css/sm-core-css.css'],
    ],
  ];
  return $libraries;
}

function simple_version_callback() {
  //use some fancy magic to get the version number... or don't
  return TRUE;
}
