<?php

/**
 * Implements hook_form_BASE_FORM_ID_form_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function halle96_forms_form_node_form_alter(&$form, &$form_state, $form_id) {
  $content_type = $form['#node']->type;
  if ($content_type == 'conference_room_paid_2' || $content_type == 'conference_room_paid_1') {
    $form['actions']['submit']['#value'] = 'Jetzt kostenpflichtig buchen';
    // A new description right above the actions buttons
    $form['actions']['#prefix'] = '<div class="description actions-description">';
    $form['actions']['#prefix'] .= 'Bitte prüfen Sie noch einmal alle Angaben. <br /> Nach dem Speichern ist die Buchung nur noch durch die Zentrumsleitung bearbeitbar.';
    $form['actions']['#prefix'] .= '</div>';
  }

  $form['field_conf_termin']['und']['#suffix'] = '<span class="time-description">Die Zeiten verstehen sich inklusive Aufbau und Abbau.</span></div>';
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function halle96_forms_form_webform_client_form_2760_alter(&$form, &$form_state, $form_id) {
  global $user;

  // Show the status field only for selected roles
  $role_yes = count(array_intersect([
    'administrator',
    'Zentrumsleitung',
    'Mitarbeiter hannoverimpuls',
  ], $user->roles));
  if ($role_yes == 0) {
    $form['submitted']['status']['#access'] = FALSE;
  }

}
