<?php

function halle96_timepicker_form_conference_room_node_form_alter(&$form, &$form_state) {
  $path = drupal_get_path('module', 'halle96_timepicker');

  dpm($form);

  // Adds a form field that the javascript utilizes or modifies.
//  $form['field_conf_termin'] = array(
//    '#type' => 'textfield',
//    '#title' => 'Your Location (Country)',
//    '#id' => 'country_autocomplete',
//    // Both the library and custom JavaScript code are added to the '#attached'
//    // property of a renderable array.
//    '#attached' => array(
//      'library' => array(
//        array('system', 'ui.timepcker'),
//      ),
//      'js' => array(
//        "$path/js/halle96_timepicker.js",
//      ),
//    ),
//  );

  $form['field_conf_termin']['#attached'] = array(
      'library' => array(
        array('system', 'ui.timepcker'),
      ),
      'js' => array(
        "$path/js/halle96_timepicker.js",
      ),
    );
}
